name: Version Update On PR
on:
  pull_request:
    branches: ["master"]
    types: ["opened"]

jobs:
  Update-Version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/checkout@v4
      - run: |
          node update-version.js
          git config user.name 'Chandan Kalita'
          git config user.email 'ck3196686@gmail.com'
          git add .
          git commit -m "auto - Version updated"
          git push
