name: Version Update On PR
on:
  pull_request:
    branches: ["master"]
    types: ["opened"]

jobs:
  Update-Version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Updating Version
        run: node update-version.js
      - name: Log
        run: echo ${{github.head_ref}}
      - name: Commit with version
        run: |
          git config --global user.name 'Chandan Kalita'
          git config --global user.email 'ck3196686@gmail.com'
          git checkout ${{github.event.pull_request.head.ref}}
          git commit -am "auto - Version updated"
          git push origin ${{github.event.pull_request.head.ref}}
